# This is a basic workflow to help you get started with Actions

name: CICD Website na VM 01 do Azure

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: TESTE

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Add SSH private key
        run: |
          pwd
          ls -l
          echo Add other actions to build,
          echo test, and deploy your project.
          echo "${{ secrets.SSHKEY }}" > chave.pem
          ls -l
          chmod 600 chave.pem

      - name: Deploy to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no -i chave.pem gestor@20.199.129.62 "sudo apt update && sudo apt install -y apache2 && sudo chown -R gestor:www-data /var/www/html"
          scp -o StrictHostKeyChecking=no -i chave.pem ./index.html gestor@20.199.129.62:/var/www/html/index.html
          scp -o StrictHostKeyChecking=no -i chave.pem ./login.html gestor@20.199.129.62:/var/www/html/login.html
          ls -l
